import Sidebar from "../components/sidebar";
// import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Montserrat } from "next/font/google";

// const queryClient = new QueryClient();
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by BCAMP",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      {/* <QueryClientProvider client={queryClient}> */}
      <div className="flex" >
        <Sidebar />
        <div className="min-h-screen flex m-auto">{children}</div>
      </div>
      {/* </QueryClientProvider>{" "} */}
    </html>
  );
}
