
import { Montserrat } from "next/font/google";
import "./globals.css";

import Header from "./components/header/header";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "TicketChain",
  description: "Generated by BCAMP",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={montserrat.className}>
      <Header/>
      {children}
      </body>
    </html>
  );
}
