import { Montserrat } from "next/font/google";
import "./globals.css";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Header from "./components/header/header";
// import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

// const queryClient = new QueryClient();
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "TicketChain",
  description: "Generated by BCAMP",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <QueryClientProvider client={queryClient}> */}
     
      <body className={montserrat.className}>
        <ToastContainer />

        <Header />
        {children}
      </body>
      {/* </QueryClientProvider>{" "} */}
    </html>
  );
}
